run:
  deadline: 3m

linters:
  disable-all: true
  enable:
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  - containedctx
  - contextcheck
  - cyclop
  - decorder
  - depguard
  - dogsled
  - dupl
  - dupword
  - durationcheck
  - errcheck
  - errchkjson
  - errname
  - errorlint
  - execinquery
  - exhaustive
  - exportloopref
  - forcetypeassert
  - funlen
  - gochecknoglobals
  - gochecknoinits
  - gocognit
  - goconst
  - gocritic
  - gocyclo
  - godot
  - godox
  - gofmt
  - goheader
  - goimports
  - gomnd
  - gomoddirectives
  - gomodguard
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - grouper
  - importas
  - ineffassign
  - interfacebloat
  - loggercheck
  - maintidx
  - makezero
  - misspell
  - nakedret
  - nestif
  - nilerr
  - noctx
  - nolintlint
  - nonamedreturns
  - nosprintfhostport
  - prealloc
  - predeclared
  - promlinter
  - reassign
  - revive
  - staticcheck
  - stylecheck
  - tenv
  - testableexamples
  - thelper
  - tparallel
  - typecheck
  - unconvert
  - unparam
  - unused
  - usestdlibvars
  - whitespace
  - wrapcheck
